name: TalAlmog
favicon: null
layout_spectrum: 0
typography_spectrum: 0.16517500765621662
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A0B0B8'
    - '#988838'
    - '#989860'
    - '#E84060'
    - '#E0E0A8'
  brandStrength: 0.10827780677936971
  lightness: 0.5801140849944204
  saturation: 0.3554220811929554
  rhythmicContrast: 0.5269317254424095
purpose: []
