name: TalAlmog
favicon: null
layout_spectrum: 0.99944
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6ab9fd'
    - '#ffffff'
    - '#b6d5ef'
    - '#93cefa'
    - '#91bee7'
  brandStrength: 0.5
  lightness: 0.5801140849944204
  saturation: 0.3554220811929554
  rhythmicContrast: 0.5269317254424095
purpose: []
